spring:
  datasource:
    url: jdbc:h2:~/batch;DB_CLOSE_ON_EXIT=FALSE
    jdbcUrl: jdbc:h2:~/batch;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always

app:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    jdbcUrl: jdbc:mysql://localhost:3306/batch
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver