spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/batch
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always