version: '3'
services:
  db:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: batch
      MYSQL_RANDOM_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /path/on/host:/var/lib/mysql